### ISSUE TITLE
Iteration 2 - Enhancements to be Completed

### ISSUE THREAD

**Issue by thomasbryk** [bearium/SYSC3303-Group-7#9]
**Requests**
- [] _FloorButtonRequest_: remove destination
- []

**Implement New Elevator/Floor Interaction**
1. Elevator stops
2. Elevator opens door
    a. Elevator sends to floor to get destination
    b. Floor empties queue, sends destinations to elevator.
3. Elevator lights buttons
4. Elevator sends each destination to Scheduler
5. Scheduler receives destination
    a. Adds to queue
    b. Checks pending requests

**Comment by dillonclaremont** [comment]
TODO

REQUESTS
- UPDATE: FloorButtonRequest
	- remove destination floor
- UPDATE: ElevatorArrivalRequest
	- add direction, this is only used when scheduler sends to the floor that an elevator is arriving at it (the scheduler provides the elevator's queue direction)
- NEW: ElevatorDestinationRequest
	- this is used when floor sends destinations to elevator AND when elevator sends destinations to scheduler
	- destinations
	- floor name
	- depending on whats easy for Mustafa, either multiple requests or a single with an array (probably preferable)
- NEW: ElevatorWaitRequest
	- doesnt need any fields
	- elevator will choose how long to wait based on the value set in config.xml

SCHEDULER
- UPDATE: trip scheduler to not have a trip destination when receiving initial trip request
- UPDATE: ElevatoorDoorRequest handling
	- when elevator door open request received
		- send elevator wait request (do not wait for confirmation) (wait for trip destination request)
- NEW: handle trip destination requests
	- match to corresponding trip request 
	- send door close request... carry on from here.. sweet
- UPDATE: logic in opened door confirmation that handles new pending requests / and determine whether elevator needs to move to the ElevatorWaitRequest event

FLOOR
- NEW: create up/down queue
	- when a trip request is created, before its serviced need to maintain the destination queues
	- when receive a elevator arrival request  

ELEVATOR
- UPDATE: add and support from config.xml
	- door open/close times
	- timebetweenfloor times
	- passenger loading time
- NEW: request handling
	- ElevatorDestinationRequest
		- light buttons
		- forward to scheduler
	- handle ElevatorWaitRequest event
		- time to sleep based on config
		- do not send confirmation

SCHEDULER/FLOOR/ELEVATOR - sequence changes
- scheduler gets floor arrival notice from elevator
- scheduler tells elevator to stop
- elevator confirms it has stopped
- scheduler tells to open door
- elevator confirms door is open
- once scheduler receives confirmation that elevator doors are open
	// the following points do not cause scheduler to wait or initiate a new event- scheduler merely handles and updates queue
	- scheduler tells floor that elevator # is stopping at this floor to go up/down in service
	- floor tells elevator which destination requests will happen based on the direction info given from scheduler
	- elevator lights its destination buttons
	- elevator tells scheduler which destination requests will happen from this floor 
- scheduler says to wait for passengers
- elevator confirms when wait is complete
